# Generated by Django 4.1.1 on 2023-01-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0002_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
